# coding: utf-8

"""
    CardForge API

    Backend API for CardForge. Authentication is handled via GitHub App OAuth flow (server-side). The backend manages GitHub tokens and interacts with GitHub on behalf of the user. 

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from fastapi import FastAPI

from openapi_server.apis.auth_api import router as AuthApiRouter
from openapi_server.apis.projects_api import router as ProjectsApiRouter
from openapi_server.apis.repos_api import router as ReposApiRouter

app = FastAPI(
    title="CardForge API",
    description="Backend API for CardForge. Authentication is handled via GitHub App OAuth flow (server-side). The backend manages GitHub tokens and interacts with GitHub on behalf of the user. ",
    version="3.0.0",
)

app.include_router(AuthApiRouter)
app.include_router(ProjectsApiRouter)
app.include_router(ReposApiRouter)
