# coding: utf-8

"""
    CardForge API

    Backend API for CardForge. Authentication is handled via GitHub App OAuth flow (server-side). The backend manages GitHub tokens and interacts with GitHub on behalf of the user. 

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.card_sheet import CardSheet
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class CardProject(BaseModel):
    """
    CardProject
    """ # noqa: E501
    id: StrictStr
    name: StrictStr
    description: StrictStr
    created_at: datetime = Field(alias="createdAt")
    slug: Optional[StrictStr] = Field(default=None, description="URL-safe slug used in the public card archive URL (/p/{slug})")
    is_public: Optional[StrictBool] = Field(default=None, description="When true, the project is viewable at /p/{slug} as a searchable public card gallery with TCG Schema microdata. ", alias="isPublic")
    sheets: List[CardSheet]
    __properties: ClassVar[List[str]] = ["id", "name", "description", "createdAt", "slug", "isPublic", "sheets"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of CardProject from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in sheets (list)
        _items = []
        if self.sheets:
            for _item in self.sheets:
                if _item:
                    _items.append(_item.to_dict())
            _dict['sheets'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of CardProject from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "description": obj.get("description"),
            "createdAt": obj.get("createdAt"),
            "slug": obj.get("slug"),
            "isPublic": obj.get("isPublic"),
            "sheets": [CardSheet.from_dict(_item) for _item in obj.get("sheets")] if obj.get("sheets") is not None else None
        })
        return _obj


