# coding: utf-8

"""
    CardForge API

    Backend API for CardForge. Authentication is handled via GitHub App OAuth flow (server-side). The backend manages GitHub tokens and interacts with GitHub on behalf of the user. 

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from openapi_server.models.card_element_style import CardElementStyle
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class CardElement(BaseModel):
    """
    CardElement
    """ # noqa: E501
    id: StrictStr
    type: StrictStr
    tag: StrictStr = Field(description="Tag name, e.g. {{name}}")
    x: Union[StrictFloat, StrictInt]
    y: Union[StrictFloat, StrictInt]
    width: Union[StrictFloat, StrictInt]
    height: Union[StrictFloat, StrictInt]
    style: CardElementStyle
    visible_if_field: Optional[StrictStr] = Field(default=None, description="Show element only when this field has a non-empty value", alias="visibleIfField")
    tcg_type: Optional[StrictStr] = Field(default=None, description="TCG Schema class URI (e.g. tcg:Card)", alias="tcgType")
    tcg_property: Optional[StrictStr] = Field(default=None, description="TCG Schema property URI (e.g. schema:name)", alias="tcgProperty")
    __properties: ClassVar[List[str]] = ["id", "type", "tag", "x", "y", "width", "height", "style", "visibleIfField", "tcgType", "tcgProperty"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in ('text', 'icon', 'image', 'hline', 'vline', 'svg',):
            raise ValueError("must be one of enum values ('text', 'icon', 'image', 'hline', 'vline', 'svg')")
        return value

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of CardElement from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of style
        if self.style:
            _dict['style'] = self.style.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of CardElement from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "type": obj.get("type"),
            "tag": obj.get("tag"),
            "x": obj.get("x"),
            "y": obj.get("y"),
            "width": obj.get("width"),
            "height": obj.get("height"),
            "style": CardElementStyle.from_dict(obj.get("style")) if obj.get("style") is not None else None,
            "visibleIfField": obj.get("visibleIfField"),
            "tcgType": obj.get("tcgType"),
            "tcgProperty": obj.get("tcgProperty")
        })
        return _obj


