# coding: utf-8

"""
    CardForge API

    Backend API for CardForge. Authentication is handled via GitHub App OAuth flow (server-side). The backend manages GitHub tokens and interacts with GitHub on behalf of the user. 

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class CardElementStyle(BaseModel):
    """
    CardElementStyle
    """ # noqa: E501
    font_size: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="fontSize")
    font_weight: Optional[StrictStr] = Field(default=None, alias="fontWeight")
    color: Optional[StrictStr] = None
    icon_name: Optional[StrictStr] = Field(default=None, alias="iconName")
    stroke_width: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="strokeWidth")
    svg_data: Optional[StrictStr] = Field(default=None, description="Base64 data URI of SVG", alias="svgData")
    image_url: Optional[StrictStr] = Field(default=None, alias="imageUrl")
    rotation: Optional[Union[StrictFloat, StrictInt]] = None
    __properties: ClassVar[List[str]] = ["fontSize", "fontWeight", "color", "iconName", "strokeWidth", "svgData", "imageUrl", "rotation"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of CardElementStyle from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of CardElementStyle from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "fontSize": obj.get("fontSize"),
            "fontWeight": obj.get("fontWeight"),
            "color": obj.get("color"),
            "iconName": obj.get("iconName"),
            "strokeWidth": obj.get("strokeWidth"),
            "svgData": obj.get("svgData"),
            "imageUrl": obj.get("imageUrl"),
            "rotation": obj.get("rotation")
        })
        return _obj


