# coding: utf-8

"""
    CardForge API

    Backend API for CardForge. Authentication is handled via GitHub App OAuth flow (server-side). The backend manages GitHub tokens and interacts with GitHub on behalf of the user. 

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.card_template import CardTemplate
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class CardSheet(BaseModel):
    """
    CardSheet
    """ # noqa: E501
    id: StrictStr
    name: StrictStr
    template: CardTemplate
    back_template: Optional[CardTemplate] = Field(default=None, alias="backTemplate")
    rows: List[Dict[str, StrictStr]]
    __properties: ClassVar[List[str]] = ["id", "name", "template", "backTemplate", "rows"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of CardSheet from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of template
        if self.template:
            _dict['template'] = self.template.to_dict()
        # override the default output from pydantic by calling `to_dict()` of back_template
        if self.back_template:
            _dict['backTemplate'] = self.back_template.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of CardSheet from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "template": CardTemplate.from_dict(obj.get("template")) if obj.get("template") is not None else None,
            "backTemplate": CardTemplate.from_dict(obj.get("backTemplate")) if obj.get("backTemplate") is not None else None,
            "rows": obj.get("rows")
        })
        return _obj


