# coding: utf-8

"""
    CardForge API

    Backend API for CardForge. Authentication is handled via GitHub App OAuth flow (server-side). The backend manages GitHub tokens and interacts with GitHub on behalf of the user. 

    The version of the OpenAPI document: 3.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.installation_account import InstallationAccount
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class Installation(BaseModel):
    """
    Installation
    """ # noqa: E501
    id: Optional[StrictInt] = Field(default=None, description="GitHub App installation ID")
    account: Optional[InstallationAccount] = None
    permissions: Optional[Dict[str, StrictStr]] = None
    repository_selection: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["id", "account", "permissions", "repository_selection"]

    @field_validator('repository_selection')
    def repository_selection_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ('all', 'selected',):
            raise ValueError("must be one of enum values ('all', 'selected')")
        return value

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of Installation from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of account
        if self.account:
            _dict['account'] = self.account.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of Installation from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "account": InstallationAccount.from_dict(obj.get("account")) if obj.get("account") is not None else None,
            "permissions": obj.get("permissions"),
            "repository_selection": obj.get("repository_selection")
        })
        return _obj


